name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  COV_THRESHOLD: 100.0
  CRATE_PATHS: .

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy      
      - name: Build
        run: cargo build --all-targets --verbose
      - name: Test
        run: cargo test --verbose

  check-coverage:
      runs-on: ubuntu-18.04
      needs: test
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 2
        - name: Install Rust toolchain
          uses: actions-rs/toolchain@v1
          with:
              toolchain: stable
              override: true
              components: rustfmt, clippy      
        - name: Install grcov
          run: cargo install grcov --debug
        - name: Run coverage
          script:
              - rustup component add llvm-tools-preview
              - export RUSTFLAGS="-Cinstrument-coverage"
              - cargo build --verbose
              - LLVM_PROFILE_FILE="your_name-%p-%m.profraw" cargo test --verbose
              - ./grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
              - bash <(curl -s https://codecov.io/bash) -f lcov.info