name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  COV_THRESHOLD: 100.0
  CRATE_PATHS: .

jobs:

  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
      - name: Build
        run: cargo build --all-targets --verbose
      - name: Test
        run: cargo test --verbose

  check-coverage:
      runs-on: ubuntu-18.04
      needs: test
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 2
        - name: Install Rust toolchain
          uses: actions-rs/toolchain@v1
          with:
            toolchain: ${{ env.RUST_VERSION_NIGHTLY }}
            profile: minimal
            components: llvm-tools-preview
            override: true
        - name: Install grcov
          run: cargo install grcov --debug
        - name: Run coverage
          run: bash .github/workflows/scripts/run_coverage.sh
        - name: Upload coverage report on GitHub
          uses: actions/upload-artifact@v2
          with:
            name: coverage
            path: coverage
            if-no-files-found: error
            retention-days: 1
        - name: Upload coverage report on Codecov
          run: bash .github/workflows/scripts/upload_coverage_on_codecov.sh
        - name: Check coverage threshold
          run: bash .github/workflows/scripts/check_coverage.sh
